### ISSUE TITLE
Failed to open file as Vorbis: Ogg bitstream does not contain a supported data-type

### ISSUE THREAD

**Issue by mafrosis** [xiph/vorbis-tools#11]
Hello, I wasn't sure where else to post this, so please close if you aren't interested..

Under both OSX and Debian, I'm seeing this error from `vorbiscomment`. The file in question was created by `opusenc` and `opusinfo` returns correct results.

Encoding a wav:

    $ opusenc tmp.wav tmp.opus
    Encoding using libopus 1.2.1 (audio)
    -----------------------------------------------------
       Input: 44.1kHz 2 channels
      Output: 2 channels (2 coupled)
              20ms packets, 96kbit/sec VBR
     Preskip: 312

    Encoding complete
    -----------------------------------------------------
           Encoded: 5 minutes and 49.36 seconds
           Runtime: 4 seconds
                    (87.34x realtime)
             Wrote: 4143923 bytes, 17468 packets, 352 pages
           Bitrate: 94.2094kbit/s (without overhead)
     Instant rates: 1.2kbit/s to 190.8kbit/s
                    (3 to 477 bytes per packet)
          Overhead: 0.719% (container+metadata)

The output of `opusinfo`:

    $ opusinfo test.opus
    Processing file "test.opus"...

    New logical stream (#1, serial: 69fda92a): type opus
    Encoded with libopus 1.2.1
    User comments section follows...
        ENCODER=opusenc from opus-tools 0.1.10
    Opus stream 1:
	    Pre-skip: 312
	    Playback gain: 0 dB
	    Channels: 2
	    Original sample rate: 44100Hz
	    Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
	    Page duration:   1000.0ms (max),  998.2ms (avg),  360.0ms (min)
	    Total data length: 4143923 bytes (overhead: 0.719%)
	    Playback length: 5m:49.349s
	    Average bitrate: 94.89 kb/s, w/o overhead: 94.21 kb/s
    Logical stream 1 ended

The error:

    $ vorbiscomment test.opus -l
    Failed to open file as Vorbis: Ogg bitstream does not contain a supported data-type.

I can share the file if anyone has time to look into this, but I'm having a hard time understanding why I'm the only person on the internet seeing this error :)

**Comment by tdaede** [comment]
Yeah, vorbiscomment currently does not support Opus streams. It would not be too hard to add, though.

**Comment by mafrosis** [comment]
Thanks @tdaede. Format noob here - I see that I should add tags at encode time with `opusenc` now..

**Comment by izderadicka** [comment]
So what is then recommended command line tool to edit comments in opus files?

**Comment by thomas-mc-work** [comment]
I was unable to find a standalone CLI application for tagging, too. Except for this which rather seems to be a hack:

    ffmpeg -i <input-file> -acodec copy -metadata title="<title>" -metadata artist=<artist> <output-file>

Apart from that there is a GUI application too: https://kid3.sourceforge.io/

**Comment by ftrebien** [comment]
@thomas-mc-work Maybe [opustags](https://github.com/fmang/opustags).
