### ISSUE TITLE
Windows - Make an update ?

### ISSUE THREAD

**Issue by Kdmeizk** [xiph/vorbis-tools#2]
From Github (vorbis-tools-master), with the folder VS2005, I built successfully. But, -h mentions version 1.3.0.

- Is it possible to update files until the latest ? I tried from vorbis-tools-1.4.0 but many hours for nothing, in comparison to Github, 10 mins and it works. I have no experience with VC++6 and I haven't it.
- Plus, I saw VS until 2010 for vorbis for example. If it requires no really more time, it would be really good to upgrade until VS2010 at least.
- Last, if it requires no really more time also for statics libraries (all from Github are in shared libraries), it would be really nice of you.

Thank you so much for your work !

**Comment by Chocobo1** [comment]
>Is it possible to update files until the latest ? I tried from vorbis-tools-1.4.0 but many hours for nothing, in comparison to Github, 10 mins and it works.

Second this.
At https://www.xiph.org/downloads/ vorbis-tools latest release is labeled `1.4.0` while on git repo: https://git.xiph.org/?p=vorbis-tools.git;a=blob;f=win32/config.h;h=a01cf0b79da3610fa230178fe504c0f8c9d71644;hb=HEAD
I only see `1.3.0`.
Typo on the xiph website?

**Comment by Kdmeizk** [comment]
Yes but the files CHANGES contains the latest 1.4.0.

**Comment by Chocobo1** [comment]
Thanks for clarifying, now I think the devs just forget to bump the version in `win32/config.h`.

**Comment by rillian** [comment]
Fixed in 9d926044b73f28ab81631300524f273e11b50faa. Thanks Chocobo1!
