### ISSUE TITLE
64-bit architecture compatibility

### ISSUE THREAD

**Issue by marcoXbresciani** [xiph/vorbis-tools#20]
Are oggenc/oggdec compatible with 64bit processors and operating systems? Can they simply be recompiled or are there other needs?

**Comment by petterreinholdtsen** [comment]
[Marco Bresciani]
> Are oggenc/oggdec compatible with 64bit processors and operating
> systems? Can they simply be recompiled or are there other needs?

As far as I can tell from 
<URL: https://buildd.debian.org/status/package.php?p=vorbis-tools >
it build and work on 64-bits systems.

--
Vennlig hilsen
Petter Reinholdtsen

**Comment by marcoXbresciani** [comment]
Yup, indeed!
