### ISSUE TITLE
Winamp (the commerical product) is violating the GPL license for vorbis-tools.

### ISSUE THREAD

**Issue by kallisti5** [xiph/vorbis-tools#50]
Just discovered in the winamp source release, they are (were?) violating the GPL around vorbis-tools:
https://github.com/WinampDesktop/winamp/blob/community/Src/Plugins/Input/in_vorbis/vcedit.c#L1

It's being discussed here:
https://github.com/WinampDesktop/winamp/issues/265#issuecomment-2377483345

This is more of an FYI to xiph.   Feel free to close if not interested.

 Thanks!

**Comment by MichaelAgarkov** [comment]
Dolby and Frauhofer as well btw.

**Comment by tdaede** [comment]
Thanks for bringing this up. vorbis-tools is LGPL, so it looks like they can come into compliance simply by including the licenses from vorbis-tools and libogg. We'd love to see as many players as possible continue to support royalty-free formats such as Ogg Vorbis.
